import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
const {JSDOM}=await import(process.env.JSDOM_MODULE||'jsdom');
async function app(options={}){let me=options.loggedOut?null:{id:'player'};const dom=new JSDOM(readFileSync('index.html','utf8'),{url:options.url||'https://antagonista13.github.io/Kron-ngs-IF-Juniorlag/',runScripts:'outside-only'});const w=dom.window;let sub=null;const cfg={posts_enabled:false,messages_enabled:false,unread_count:0,public_key:'A'.repeat(87),delivery_enabled:false};let fail=false,chatOpened=null,savedPreferences=null;
w.isSecureContext=true;w.PushManager=function(){};w.matchMedia=()=>({matches:true});w.Notification={permission:'granted',requestPermission:async()=> 'granted'};
const reg={pushManager:{getSubscription:async()=>sub,subscribe:async()=>{sub={endpoint:'https://web.push.apple.com/dom-fixture',toJSON:()=>({endpoint:sub.endpoint,keys:{p256dh:'A'.repeat(87),auth:'B'.repeat(22)}}),unsubscribe:async()=>{sub=null;return true;}};return sub;}}};Object.defineProperty(w.navigator,'serviceWorker',{value:{register:async()=>reg,getRegistration:async()=>reg,ready:Promise.resolve(reg)}});
w.kronangSupabase={auth:{getUser:async()=>({data:{user:me}})},from(table){const q={select(){return q;},eq(){return q;},single:async()=>({data:{id:'player',role:options.role||'player',is_active:true,team:'KIF'}}),maybeSingle:async()=>({data:options.missing?null:table==='team_posts'?{id:'11111111-1111-4111-8111-111111111111',team:'KIF'}:table==='player_chat_messages'?{conversation_id:'conversation-1'}:table==='player_chat_conversations'?{player_id:'roster-player-1'}:table==='players'?{id:'roster-player-1',full_name:'Testspelare'}:{id:'subscription',enabled:true}})};return q;},rpc:async(name,args)=>{if(name==='get_push_status')return{data:cfg};if(name==='register_push_subscription')return fail?{error:new Error('Registreringen misslyckades. Försök igen.') }:{data:'subscription'};if(name==='set_push_preferences'){savedPreferences=args;cfg.posts_enabled=args.posts;cfg.messages_enabled=args.messages;}return{data:{}};}};
if(w.document.readyState==='loading')await new Promise(r=>w.document.addEventListener('DOMContentLoaded',r,{once:true}));
w.KronangPlayerChat={open:async args=>{chatOpened=args;}};w.KronangPlayerChatData={ownPlayerId:async()=> 'roster-player-1'};
w.eval(readFileSync('push-routing.js','utf8'));w.eval(readFileSync('push-subscriptions.js','utf8'));w.eval(readFileSync('push-notifications.js','utf8'));await w.KronangPushNotifications.refresh();return{w,dom,getChat:()=>chatOpened,getPreferences:()=>savedPreferences,setFail:value=>fail=value,signIn:()=>{me={id:'player'};}};}
const settle=()=>new Promise(r=>setTimeout(r,40));
test('actual Profile card has accessible controls and disabled rollout test',async()=>{const f=await app(),d=f.w.document;assert.equal(d.getElementById('pushNotificationsCard').hidden,false);assert.equal(d.getElementById('pushActivate').textContent,'Aktivera notiser');assert.equal(d.querySelector('label input#pushPosts').type,'checkbox');d.getElementById('pushActivate').click();await settle();assert.equal(d.getElementById('pushActivate').hidden,true);assert.equal(d.getElementById('pushTest').disabled,true);assert.equal(d.getElementById('pushDisable').hidden,false);f.dom.window.close();});
test('actual Profile restores activation button after failed registration',async()=>{const f=await app(),d=f.w.document;f.setFail(true);d.getElementById('pushActivate').click();await settle();assert.equal(d.getElementById('pushActivate').hidden,false);assert.equal(d.getElementById('pushActivate').disabled,false);assert.match(d.getElementById('pushState').textContent,/Försök igen/);f.dom.window.close();});

const destination='https://antagonista13.github.io/Kron-ngs-IF-Juniorlag/?push_kind=post&push_source=11111111-1111-4111-8111-111111111111';
test('logged-out destination resumes after login and opens real expanded post',async()=>{const f=await app({url:destination,loggedOut:true}),w=f.w;assert.equal(w.document.querySelector('[data-post-id]'),null);assert.ok(w.sessionStorage.getItem('kif-push-destination'));w.HTMLElement.prototype.scrollIntoView=function(){};
w.eval(readFileSync('team-post-compact.js','utf8'));
const source=readFileSync('team-posts.js','utf8');w.eval(source.slice(source.indexOf('function openHomeNewsPost('),source.indexOf('function setupHomeNewsNavigation(')));
w.loadTeamPosts=async()=>{const el=w.document.createElement('section');el.className='team-post';el.dataset.postId='11111111-1111-4111-8111-111111111111';el.innerHTML='<h3>Fixture</h3><p>Body</p>';let list=w.document.getElementById('teamPostsList');if(!list){list=w.document.createElement('div');list.id='teamPostsList';w.document.getElementById('teamPage').appendChild(list);}list.appendChild(el);w.KronangCompactTeamPosts.enhanceCompactTeamPost(el);};
const preview=w.document.getElementById('homeNewsCard');preview.dataset.postId='11111111-1111-4111-8111-111111111111';
f.signIn();await w.KronangPushNotifications.refresh();assert.equal(w.document.querySelector('#teamPostsList .team-post[data-post-id]').getAttribute('aria-expanded'),'true');assert.equal(w.sessionStorage.getItem('kif-push-destination'),null);assert.equal(new URL(w.location.href).searchParams.has('push_source'),false);w.close();});
test('inaccessible destination gives clear message and never opens content',async()=>{const f=await app({url:destination,missing:true});assert.match(f.w.document.getElementById('pushRouteMessage').textContent,/inte längre|inte tillgängligt/);assert.equal(f.w.document.querySelector('[data-post-id]'),null);f.w.close();});

for(const role of ['coach','admin'])test(role+' can activate message-only notifications',async()=>{const f=await app({role}),d=f.w.document;try{assert.equal(d.getElementById('pushNotificationsCard').hidden,false);assert.equal(d.getElementById('pushPosts').closest('label').hidden,true);d.getElementById('pushActivate').click();await settle();assert.deepEqual(JSON.parse(JSON.stringify(f.getPreferences())),{posts:false,messages:true});}finally{f.w.close();}});
test('leader notification opens the source players conversation',async()=>{const f=await app({role:'coach',url:'https://antagonista13.github.io/Kron-ngs-IF-Juniorlag/?push_kind=message&push_source=11111111-1111-4111-8111-111111111111'});try{assert.deepEqual(JSON.parse(JSON.stringify(f.getChat())),{playerId:'roster-player-1',playerName:'Testspelare'});assert.equal(f.w.sessionStorage.getItem('kif-push-destination'),null);}finally{f.w.close();}});
test('parent cannot activate push notifications',async()=>{const f=await app({role:'parent'});try{assert.equal(f.w.document.getElementById('pushNotificationsCard').hidden,true);}finally{f.w.close();}});
test('inaccessible leader message cannot open another chat',async()=>{const f=await app({role:'admin',missing:true,url:'https://antagonista13.github.io/Kron-ngs-IF-Juniorlag/?push_kind=message&push_source=11111111-1111-4111-8111-111111111111'});try{assert.equal(f.getChat(),null);assert.match(f.w.document.getElementById('pushRouteMessage').textContent,/inte längre|inte tillgängligt/);}finally{f.w.close();}});
