create table if not exists public.team_staff (
  id bigint generated by default as identity primary key,
  team text not null,
  display_name text not null,
  staff_role text not null,
  phone text,
  email text,
  avatar_url text,
  sort_order integer not null default 100,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.team_staff enable row level security;

drop policy if exists "team staff readable by same team" on public.team_staff;
create policy "team staff readable by same team"
on public.team_staff
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.team = team_staff.team
  )
);
