function isActiveAdmin(profile){return !!(profile&&profile.role==='admin'&&profile.is_active===true);}
function githubStatusFromRun(run){if(!run)return{state:'unknown',label:'OKÄND'};if(run.status&&run.status!=='completed')return{state:'warning',label:'VARNING'};if(run.conclusion==='success')return{state:'green',label:'GRÖN'};if(run.conclusion)return{state:'red',label:'FEL'};return{state:'unknown',label:'OKÄND'};}
function syncStatusFromRun(run){if(!run)return{state:'unknown',label:'OKÄND'};if(run.status==='success')return{state:'green',label:'GRÖN'};if(run.status==='failure')return{state:'red',label:'FEL'};return{state:'unknown',label:'OKÄND'};}
function formatAdminCenterTime(value){if(!value)return'Ingen körning ännu';const d=new Date(value);if(Number.isNaN(d.getTime()))return'Okänd tid';return new Intl.DateTimeFormat('sv-SE',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Stockholm'}).format(d);}
function setCard(id,status,title,detail){const card=document.getElementById(id);if(!card)return;card.dataset.state=status.state;const badge=card.querySelector('[data-admincenter-status]'),heading=card.querySelector('[data-admincenter-title]'),text=card.querySelector('[data-admincenter-detail]');if(badge)badge.textContent=status.label;if(heading)heading.textContent=title;if(text)text.textContent=detail||'';}
async function getCurrentAdmin(){const sb=window.kronangSupabase;const sessionResult=await sb.auth.getSession();const session=sessionResult.data&&sessionResult.data.session;if(!session)return null;const result=await sb.from('profiles').select('role,is_active').eq('id',session.user.id).maybeSingle();if(result.error||!isActiveAdmin(result.data))return null;return{profile:result.data,session};}
async function loadSyncRun(){const sb=window.kronangSupabase;const result=await sb.from('sportadmin_sync_runs').select('started_at,finished_at,status,found,imported,source,error_message,triggered_by').order('finished_at',{ascending:false}).limit(1).maybeSingle();if(result.error)throw result.error;const run=result.data||null,status=syncStatusFromRun(run);const detail=run?`${formatAdminCenterTime(run.finished_at)} · Hittade ${run.found||0} · Importerade ${run.imported||0}${run.triggered_by==='admin'?' · Manuell':' · Automatisk'}`:'Ingen registrerad körning ännu';setCard('adminCenterSportAdmin',status,'SportAdmin-synk',detail);return run;}
async function loadSupabaseStatus(admin){if(admin)setCard('adminCenterSupabase',{state:'green',label:'GRÖN'},'Supabase','Inloggning och adminprofil fungerar.');else setCard('adminCenterSupabase',{state:'red',label:'FEL'},'Supabase','Kunde inte verifiera aktiv adminprofil.');}
async function loadGithubStatus(){try{const response=await fetch('https://api.github.com/repos/Antagonista13/Kron-ngs-IF-Juniorlag/actions/runs?per_page=20',{headers:{Accept:'application/vnd.github+json'}});if(!response.ok)throw new Error('GitHub unavailable');const payload=await response.json(),runs=payload.workflow_runs||[];const relevant=runs.find(r=>['Home and news tests','SportAdmin roster sync tests','pages build and deployment'].includes(r.name))||runs[0]||null,status=githubStatusFromRun(relevant);setCard('adminCenterGithub',status,'GitHub / deployment',relevant?`${relevant.name}: ${relevant.conclusion||relevant.status||'okänd'}`:'Ingen körning hittades.');return relevant;}catch(error){setCard('adminCenterGithub',{state:'unknown',label:'OKÄND'},'GitHub / deployment','GitHub-status kunde inte hämtas just nu.');return null;}}
async function refresh(){if(typeof window==='undefined'||!window.kronangSupabase)return false;const admin=await getCurrentAdmin();const section=document.getElementById('adminCenterSection');if(section)section.hidden=!admin;if(!admin)return false;await loadSupabaseStatus(admin);try{await loadSyncRun();}catch(error){setCard('adminCenterSportAdmin',{state:'red',label:'FEL'},'SportAdmin-synk','Synkhistoriken kunde inte hämtas.');}await loadGithubStatus();return true;}
function wireManualSync(){const button=document.getElementById('adminCenterSyncNow'),message=document.getElementById('adminCenterMessage');if(!button||button.dataset.ready)return;button.dataset.ready='true';button.addEventListener('click',async()=>{button.disabled=true;const original=button.textContent;button.textContent='SYNKAR…';if(message)message.textContent='Startar SportAdmin-synk…';try{const admin=await getCurrentAdmin();if(!admin)throw new Error('Admin krävs');const result=await window.kronangSupabase.functions.invoke('sportadmin-roster-sync',{body:{trigger:'admincenter'}});if(result.error)throw result.error;const data=result.data||{};if(data.ok===false)throw new Error(data.message||'Synk misslyckades');if(message)message.textContent=`Synk klar. Hittade ${data.found||0}, importerade ${data.imported||0}.`;await loadSyncRun();}catch(error){if(message)message.textContent='SportAdmin-synken kunde inte genomföras.';setCard('adminCenterSportAdmin',{state:'red',label:'FEL'},'SportAdmin-synk','Den manuella synken misslyckades.');}finally{button.disabled=false;button.textContent=original;}});}
async function init(){if(typeof document==='undefined'||typeof window==='undefined')return;wireManualSync();await refresh();}
const adminCenterApi={isActiveAdmin,githubStatusFromRun,syncStatusFromRun,formatAdminCenterTime,refresh,init};
if(typeof module!=='undefined'&&module.exports)module.exports=adminCenterApi;
if(typeof window!=='undefined'){window.KronangAdminCenter=adminCenterApi;if(typeof document!=='undefined'){document.addEventListener('kronang:auth-signed-in',init);document.addEventListener('kronang:auth-signed-out',()=>{const section=document.getElementById('adminCenterSection');if(section)section.hidden=true;});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();}}
