/* =========================
   KRONÄNGS IF - INLOGGNING
   Supabase Auth
========================= */
const AUTH_SUPABASE_URL="https://ndbwnsiqcnxppikdrwvd.supabase.co";
const AUTH_SUPABASE_ANON_KEY="sb_publishable_LueK_yc8XAevJC9zMMVktg_hRc1Zdac";
function startKronangAuth(){
 const supabaseClient=window.supabase.createClient(AUTH_SUPABASE_URL,AUTH_SUPABASE_ANON_KEY);window.kronangSupabase=supabaseClient;
 const loginScreen=document.createElement("div");loginScreen.id="loginScreen";loginScreen.innerHTML=`<div class="login-box"><div class="login-logo"><img src="20260605_154224349_iOS.jpg" alt="Kronängs IF logotyp"></div><h1>KRONÄNGS IF</h1><p class="login-subtitle">JUNIORLAG</p><div class="login-form"><div id="signupNameField" hidden><label for="signupName">Namn</label><input id="signupName" type="text" autocomplete="name" placeholder="För- och efternamn"></div><div id="emailField"><label for="loginEmail">E-post</label><input id="loginEmail" type="email" autocomplete="username" placeholder="Din e-postadress"></div><div id="passwordField"><label for="loginPassword">Lösenord</label><input id="loginPassword" type="password" autocomplete="current-password" placeholder="Ditt lösenord"></div><div id="recoveryFields" hidden><label for="newPassword">Nytt lösenord</label><input id="newPassword" type="password" autocomplete="new-password" placeholder="Nytt lösenord"><label for="confirmPassword">Bekräfta nytt lösenord</label><input id="confirmPassword" type="password" autocomplete="new-password" placeholder="Bekräfta nytt lösenord"></div><button id="forgotPasswordButton" class="login-secondary login-forgot" type="button">GLÖMT LÖSENORD?</button><button id="loginButton" type="button">LOGGA IN</button><button id="authModeToggle" class="login-secondary" type="button">Skapa konto</button><p id="loginMessage" class="login-message"></p></div></div>`;document.body.appendChild(loginScreen);
 const emailInput=document.getElementById("loginEmail"),passwordInput=document.getElementById("loginPassword"),nameInput=document.getElementById("signupName"),nameField=document.getElementById("signupNameField"),emailField=document.getElementById("emailField"),passwordField=document.getElementById("passwordField"),recoveryFields=document.getElementById("recoveryFields"),newPasswordInput=document.getElementById("newPassword"),confirmPasswordInput=document.getElementById("confirmPassword"),forgotPasswordButton=document.getElementById("forgotPasswordButton"),loginButton=document.getElementById("loginButton"),modeToggle=document.getElementById("authModeToggle"),loginMessage=document.getElementById("loginMessage");
 let mode="login";
 function clearPassword(){if(typeof window.clearKronangLoginPassword==="function")window.clearKronangLoginPassword(passwordInput);else passwordInput.value="";newPasswordInput.value="";confirmPasswordInput.value="";}
 function setMode(next){mode=next;const signup=mode==="signup",recovery=mode==="recovery";nameField.hidden=!signup;emailField.hidden=recovery;passwordField.hidden=recovery;recoveryFields.hidden=!recovery;forgotPasswordButton.hidden=mode!=="login";modeToggle.hidden=recovery;loginButton.textContent=recovery?"SPARA NYTT LÖSENORD":signup?"SKAPA KONTO":"LOGGA IN";modeToggle.textContent=signup?"Jag har redan ett konto":"Skapa konto";passwordInput.autocomplete=signup?"new-password":"current-password";loginMessage.textContent="";loginMessage.classList.remove("success");}
 function showLogin(){clearPassword();loginScreen.style.display="flex";document.body.classList.add("login-locked");loginButton.disabled=false;loginButton.textContent=mode==="recovery"?"SPARA NYTT LÖSENORD":mode==="signup"?"SKAPA KONTO":"LOGGA IN";}
 function hideLogin(){loginScreen.style.display="none";document.body.classList.remove("login-locked");}
 function recoveryRedirectUrl(){return window.location.origin+window.location.pathname;}
 async function checkSession(){const{data}=await supabaseClient.auth.getSession();if(data.session&&mode!=="recovery")hideLogin();else showLogin();}
 modeToggle.addEventListener("click",function(){setMode(mode==="login"?"signup":"login");});
 forgotPasswordButton.addEventListener("click",async function(){const email=emailInput.value.trim();loginMessage.classList.remove("success");if(!email){loginMessage.textContent="Fyll i din e-postadress först.";emailInput.focus();return;}forgotPasswordButton.disabled=true;forgotPasswordButton.textContent="SKICKAR...";const{error}=await supabaseClient.auth.resetPasswordForEmail(email,{redirectTo:recoveryRedirectUrl()});forgotPasswordButton.disabled=false;forgotPasswordButton.textContent="GLÖMT LÖSENORD?";if(error){console.error("Lösenordsåterställning misslyckades:",error);loginMessage.textContent="Kunde inte skicka återställningsmejlet. Försök igen.";return;}loginMessage.textContent="Återställningsmejl skickat. Öppna länken i mejlet för att välja ett nytt lösenord.";loginMessage.classList.add("success");});
 loginButton.addEventListener("click",async function(){if(mode==="recovery"){const newPassword=newPasswordInput.value,confirmPassword=confirmPasswordInput.value;if(!newPassword||!confirmPassword){loginMessage.textContent="Fyll i och bekräfta ditt nya lösenord.";return;}if(newPassword!==confirmPassword){loginMessage.textContent="Lösenorden matchar inte.";return;}if(newPassword.length<6){loginMessage.textContent="Lösenordet måste vara minst 6 tecken.";return;}loginButton.disabled=true;loginButton.textContent="SPARAR...";const{error}=await supabaseClient.auth.updateUser({password:newPassword});if(error){console.error("Kunde inte uppdatera lösenord:",error);loginMessage.textContent="Kunde inte spara det nya lösenordet. Öppna återställningslänken igen och försök.";loginButton.disabled=false;loginButton.textContent="SPARA NYTT LÖSENORD";return;}clearPassword();setMode("login");await supabaseClient.auth.signOut();showLogin();loginMessage.textContent="Lösenordet är ändrat. Logga in med ditt nya lösenord.";loginMessage.classList.add("success");return;}const email=emailInput.value.trim(),password=passwordInput.value,name=nameInput.value.trim();if(!email||!password||(mode==="signup"&&!name)){loginMessage.textContent=mode==="signup"?"Fyll i namn, e-post och lösenord.":"Fyll i både e-post och lösenord.";return;}loginButton.disabled=true;loginMessage.textContent="";loginMessage.classList.remove("success");if(mode==="signup"){loginButton.textContent="SKAPAR KONTO...";const{error}=await supabaseClient.auth.signUp({email,password,options:{data:{full_name:name.trim()}}});clearPassword();if(error){console.error("Registreringsfel:",error);loginMessage.textContent="Kontot kunde inte skapas. Kontrollera uppgifterna och försök igen.";loginButton.disabled=false;loginButton.textContent="SKAPA KONTO";return;}loginMessage.textContent="Kontot är skapat och väntar på godkännande.";loginMessage.classList.add("success");loginButton.disabled=false;loginButton.textContent="SKAPA KONTO";return;}loginButton.textContent="LOGGAR IN...";const{error}=await supabaseClient.auth.signInWithPassword({email,password});if(error){console.error("Inloggningsfel:",error);loginMessage.textContent="Fel e-post eller lösenord.";clearPassword();loginButton.disabled=false;loginButton.textContent="LOGGA IN";return;}clearPassword();loginButton.textContent="INLOGGAD";hideLogin();});
 passwordInput.addEventListener("keydown",function(event){if(event.key==="Enter")loginButton.click();});
 confirmPasswordInput.addEventListener("keydown",function(event){if(event.key==="Enter")loginButton.click();});
 supabaseClient.auth.onAuthStateChange(function(event,session){if(event==="PASSWORD_RECOVERY"){setMode("recovery");loginScreen.style.display="flex";document.body.classList.add("login-locked");}else if(session&&mode!=="recovery")hideLogin();else if(!session&&mode!=="recovery")showLogin();if(typeof window.handleKronangAuthNavigation==="function")window.handleKronangAuthNavigation(event,session);});
 checkSession();
}
function loadSupabaseAuthLibrary(){if(window.supabase){startKronangAuth();return;}const script=document.createElement("script");script.src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2";script.onload=startKronangAuth;script.onerror=function(){console.error("Kunde inte ladda Supabase Auth.");};document.head.appendChild(script);}
const authStyle=document.createElement("style");authStyle.textContent=`#loginScreen{position:fixed;inset:0;z-index:99999;background:#080808;color:#fff;display:none;align-items:center;justify-content:center;padding:20px}.login-box{width:100%;max-width:380px;background:#fff;color:#080808;border-radius:24px;padding:30px 24px;box-shadow:0 15px 45px rgba(0,0,0,.35)}.login-logo{width:76px;height:76px;margin:0 auto 18px;border-radius:18px;overflow:hidden}.login-logo img{width:100%;height:100%;object-fit:cover}.login-box h1{margin:0;text-align:center;font-size:22px;letter-spacing:1.5px}.login-subtitle{margin:6px 0 28px;text-align:center;color:#777;font-size:11px;letter-spacing:3px}.login-form{display:flex;flex-direction:column}.login-form label{display:block;font-size:12px;font-weight:700;margin:0 0 6px}.login-form input{width:100%;border:1px solid #ddd;border-radius:12px;padding:14px;font-size:16px;margin-bottom:16px;outline:none;box-sizing:border-box}#loginButton{border:none;border-radius:12px;background:#080808;color:#fff;padding:15px;font-size:14px;font-weight:800;cursor:pointer}#loginButton:disabled{opacity:.6}.login-secondary{border:0;background:transparent;color:#555;padding:12px;font-weight:700;cursor:pointer}.login-secondary:disabled{opacity:.55}.login-forgot{align-self:flex-end;padding:0 0 14px;font-size:12px}.login-message{min-height:20px;margin:8px 0 0;text-align:center;color:#8b0000;font-size:13px}.login-message.success{color:#246b3b}body.login-locked{overflow:hidden}`;document.head.appendChild(authStyle);loadSupabaseAuthLibrary();
