(function(){
const FEED='https://kronangs-kalender.h-bergqvist.workers.dev/';
function esc(value){return String(value||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');}
function value(block,field){const m=block.match(new RegExp('^'+field+'[^:]*:(.*)$','m'));return m?m[1].trim():'';}
function parseDate(raw){const m=String(raw||'').match(/(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})/);return m?new Date(+m[1],+m[2]-1,+m[3],+m[4],+m[5]):null;}
function parse(ics){return(ics.match(/BEGIN:VEVENT[\s\S]*?END:VEVENT/g)||[]).map(block=>({date:parseDate(value(block,'DTSTART')),summary:value(block,'SUMMARY'),location:value(block,'LOCATION'),description:value(block,'DESCRIPTION')})).filter(item=>item.date instanceof Date&&!Number.isNaN(item.date.getTime()));}
function typeFor(title){const t=String(title||'').toLowerCase();if(t.includes('match'))return['MATCH','⚽','match'];if(t.includes('träning'))return['TRÄNING','🏃','training'];if(t.includes('domar'))return['UPPDRAG','🟨','other'];return['ÖVRIGT','📋','other'];}
function card(item,isNext){const [type,icon,cls]=typeFor(item.summary);const date=item.date.toLocaleDateString('sv-SE',{weekday:'long',day:'numeric',month:'long'}).toUpperCase();const time=item.date.toLocaleTimeString('sv-SE',{hour:'2-digit',minute:'2-digit'});const title=String(item.summary||'Aktivitet').replace(/^Match:\s*/i,'').replace(/\s*\([^)]*\)\s*$/,'');const meeting=(String(item.description||'').match(/Samling:\s*([0-9]{1,2}:[0-9]{2})/i)||[])[1]||'';return `<div class="calendar-card ${cls} ${isNext?'next-activity':''}">${isNext?'<div class="next-activity-label">⭐ NÄSTA AKTIVITET</div>':''}<div class="calendar-card-date">${esc(date)}</div><div class="calendar-card-type"><span>${icon}</span>${type}</div><div class="calendar-card-title">${esc(title)}</div><div class="calendar-card-details"><div>🕒 ${esc(time)}</div>${meeting?`<div>👥 Samling: ${esc(meeting)}</div>`:''}${item.location?`<div>📍 ${esc(item.location)}</div>`:''}</div></div>`;}
async function renderCalendarBridge(){const host=document.getElementById('calendarList');if(!host)return;host.innerHTML='<div class="calendar-loading">Hämtar aktiviteter från SportAdmin...</div>';try{const response=await fetch(FEED,{cache:'default'});if(!response.ok)throw new Error('calendar bridge fetch failed: '+response.status);const now=new Date();const items=parse(await response.text()).filter(item=>item.date>=now).sort((a,b)=>a.date-b.date).slice(0,10);if(!items.length){host.innerHTML='<div class="calendar-loading">Inga kommande aktiviteter hittades.</div>';return;}let html=card(items[0],true);if(items.length>1)html+='<div class="calendar-section-title">KOMMANDE AKTIVITETER</div>'+items.slice(1).map(item=>card(item,false)).join('');host.innerHTML=html;}catch(error){console.error('Calendar bridge failed',error);host.innerHTML='<div class="calendar-loading error">Kunde inte läsa kalendern från SportAdmin.</div>';}}
window.testSportAdminCalendar=renderCalendarBridge;
})();
