(function(){
const FEED='https://kronangs-kalender.h-bergqvist.workers.dev/';
function value(block,field){const m=block.match(new RegExp('^'+field+'[^:]*:(.*)$','m'));return m?m[1].trim():'';}
function parseDate(raw){const m=String(raw||'').match(/(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})/);return m?new Date(+m[1],+m[2]-1,+m[3],+m[4],+m[5]):null;}
function parseActivities(ics){const cm=window.KronangCalendarManagement;return(ics.match(/BEGIN:VEVENT[\s\S]*?END:VEVENT/g)||[]).map(block=>{const a={uid:value(block,'UID'),startRaw:value(block,'DTSTART'),endRaw:value(block,'DTEND'),summary:value(block,'SUMMARY'),location:value(block,'LOCATION'),description:value(block,'DESCRIPTION')};a.date=parseDate(a.startRaw);a.endDate=parseDate(a.endRaw);a.externalKey=cm.stableExternalEventKey(a);return a;});}
function typeFor(title){const t=String(title||'').toLowerCase();if(t.includes('match'))return['MATCH','⚽','match'];if(t.includes('träning'))return['TRÄNING','🏃','training'];return['ÖVRIGT','📋','other'];}
function card(activity,isNext,canHide){const cm=window.KronangCalendarManagement,esc=cm.escapeCalendarHtml;const [type,icon,cls]=typeFor(activity.summary);const date=activity.date.toLocaleDateString('sv-SE',{weekday:'long',day:'numeric',month:'long'}).toUpperCase();const time=activity.date.toLocaleTimeString('sv-SE',{hour:'2-digit',minute:'2-digit'});const title=String(activity.summary||'Aktivitet').replace(/^Match:\s*/i,'').replace(/\s*\([^)]*\)\s*$/,'');const meeting=(activity.description.match(/Samling:\s*([0-9]{1,2}:[0-9]{2})/i)||[])[1]||'';return `<div class="calendar-card ${cls} ${isNext?'next-activity':''}" data-calendar-key="${esc(activity.externalKey)}">${isNext?'<div class="next-activity-label">⭐ NÄSTA AKTIVITET</div>':''}<div class="calendar-card-date">${esc(date)}</div><div class="calendar-card-type"><span>${icon}</span>${type}</div><div class="calendar-card-title">${esc(title)}</div><div class="calendar-card-details"><div>🕒 ${esc(time)}</div>${meeting?`<div>👥 Samling: ${esc(meeting)}</div>`:''}${activity.location?`<div>📍 ${esc(activity.location)}</div>`:''}</div>${canHide?'<button type="button" class="calendar-hide-button">DÖLJ AKTIVITET</button>':''}</div>`;}
async function fetchVisible(){const r=await fetch(FEED);if(!r.ok)throw new Error('calendar fetch failed');const all=parseActivities(await r.text());const cm=window.KronangCalendarManagement;const hidden=await cm.loadHiddenCalendarKeys();return cm.filterCurrentOrFutureActivities(cm.filterHiddenActivities(all,hidden),new Date()).sort((a,b)=>a.date-b.date);}
async function renderHiddenAdmin(host){const cm=window.KronangCalendarManagement,esc=cm.escapeCalendarHtml;const profile=await cm.getCalendarProfile();if(!cm.canRestoreCalendarForProfile(profile))return;const wrap=document.createElement('section');wrap.className='calendar-hidden-admin';wrap.innerHTML='<button type="button" class="calendar-show-hidden">VISA DOLDA AKTIVITETER</button><div class="calendar-hidden-list" hidden></div>';host.appendChild(wrap);wrap.querySelector('.calendar-show-hidden').addEventListener('click',async()=>{const list=wrap.querySelector('.calendar-hidden-list');const rows=await cm.listHiddenCalendarActivities();list.hidden=false;list.innerHTML=rows.length?rows.map(r=>`<div class="calendar-hidden-row"><div><strong>${esc(r.title||'Aktivitet')}</strong><small>${esc(r.start_at?new Date(r.start_at).toLocaleString('sv-SE'):'')}</small></div><button type="button" data-restore-id="${esc(r.id)}">ÅTERSTÄLL</button></div>`).join(''):'<p>Inga dolda aktiviteter.</p>';list.querySelectorAll('[data-restore-id]').forEach(btn=>btn.addEventListener('click',async()=>{if(await cm.restoreCalendarActivity(btn.dataset.restoreId)){await window.testSportAdminCalendar();await window.loadNextActivityHome();}}));});}
window.testSportAdminCalendar=async function(){const host=document.getElementById('calendarList');if(!host)return;host.innerHTML='<div class="calendar-loading">Hämtar aktiviteter från SportAdmin...</div>';try{const cm=window.KronangCalendarManagement;const profile=await cm.getCalendarProfile();const canHide=cm.canHideCalendarForProfile(profile);const items=(await fetchVisible()).slice(0,10);if(!items.length){host.innerHTML='<div class="calendar-loading">Inga kommande aktiviteter hittades.</div>';await renderHiddenAdmin(host);return;}let html=card(items[0],true,canHide);if(items.length>1)html+='<div class="calendar-section-title">KOMMANDE AKTIVITETER</div>'+items.slice(1).map(a=>card(a,false,canHide)).join('');host.innerHTML=html;if(canHide)host.querySelectorAll('.calendar-hide-button').forEach(btn=>btn.addEventListener('click',async()=>{const el=btn.closest('[data-calendar-key]');const activity=items.find(a=>a.externalKey===el.dataset.calendarKey);if(activity&&window.confirm(`Dölj aktiviteten ”${activity.summary||'Aktivitet'}” i appen?`)){if(await cm.hideCalendarActivity(activity)){await window.testSportAdminCalendar();await window.loadNextActivityHome();}}}));await renderHiddenAdmin(host);}catch(e){console.error(e);host.innerHTML='<div class="calendar-loading error">Kunde inte läsa kalendern från SportAdmin.</div>';}};
function notifyNextActivityUpdated(){document.dispatchEvent(new CustomEvent('kronang:next-activity-updated'));}
window.loadNextActivityHome=async function(){const host=document.getElementById('nextActivityHome');if(!host)return;try{const cm=window.KronangCalendarManagement,esc=cm.escapeCalendarHtml;const item=(await fetchVisible())[0];if(!item){host.innerHTML='<strong>Ingen kommande aktivitet</strong><p>Kalendern uppdateras automatiskt.</p>';notifyNextActivityUpdated();return;}const [type,icon]=typeFor(item.summary);const title=String(item.summary||'Aktivitet').replace(/^Match:\s*/i,'');const date=item.date.toLocaleDateString('sv-SE',{weekday:'long',day:'numeric',month:'long'});const time=item.date.toLocaleTimeString('sv-SE',{hour:'2-digit',minute:'2-digit'});host.innerHTML=`<div class="activity-icon">${icon}</div><div class="next-activity-info"><div class="next-activity-type">${type}</div><strong>${esc(title)}</strong><p>${esc(date)} · ${esc(time)}</p>${item.location?`<div class="activity-location">📍 ${esc(item.location)}</div>`:''}</div>`;notifyNextActivityUpdated();}catch(e){console.error(e);host.innerHTML='<strong>Kalendern kunde inte laddas</strong><p>Försök igen senare.</p>';notifyNextActivityUpdated();}};
window.loadNextActivityHome();
})();
