(function(root){
function leader(role){return role==='admin'||role==='coach';}
function canRegisterDevelopmentFollowUp(role){return leader(role);}
function canProposeDevelopmentGoal(role){return leader(role);}
function canEditOwnDevelopmentGoal(role,ownsPlayer){return role==='player'&&Boolean(ownsPlayer);}
function buildDevelopmentProfileModel(input){input=input||{};const role=input.role||'';const allowed=leader(role)||role==='player';if(!allowed)return{allowed:false,entries:[],canFollowUp:false,canPropose:false};let entries=input.entries||[];if(role==='player')entries=entries.filter(x=>x.visibility==='player_visible');return{allowed:true,player:input.player||null,goal:input.goal||null,focus:input.focus||null,proposal:input.proposal||null,entries,canFollowUp:leader(role),canPropose:leader(role),canEditGoal:canEditOwnDevelopmentGoal(role,Boolean(input.ownsPlayer))};}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function dateText(v){if(!v)return'Ingen uppföljning ännu';const d=new Date(v);return Number.isNaN(d.getTime())?'Ingen uppföljning ännu':new Intl.DateTimeFormat('sv-SE',{day:'numeric',month:'short',year:'numeric',timeZone:'Europe/Stockholm'}).format(d);}
async function fetchData(playerId,profileId){const db=root.kronangSupabase;const [entries,proposals,goal,focus]=await Promise.all([db.from('development_entries').select('*').eq('player_id',playerId).order('created_at',{ascending:false}),db.from('development_goal_proposals').select('*').eq('player_id',playerId).order('created_at',{ascending:false}),profileId?db.from('development_goals').select('*').eq('player_id',profileId).eq('status','active').order('created_at',{ascending:false}).limit(1).maybeSingle():Promise.resolve({data:null}),profileId?db.from('development_focuses').select('*').eq('player_id',profileId).eq('lifecycle_status','active').order('created_at',{ascending:false}).limit(1).maybeSingle():Promise.resolve({data:null})]);return{entries:entries.data||[],proposal:(proposals.data||[]).find(x=>x.status==='pending')||null,goal:goal.data||null,focus:focus.data||null};}
async function openPlayerDevelopmentWorkflow(opts){if(!root||!root.kronangSupabase||!opts||!opts.container)return;const c=opts.container,role=opts.role,player=opts.player,profileId=player.profile_id||opts.profileId||null;c.innerHTML='<p>Hämtar utvecklingsprofil...</p>';try{const data=await fetchData(player.id,profileId),follow=data.entries.find(x=>x.entry_type==='follow_up');let html=`<section class="development-workflow-profile"><header><span class="development-kicker">UTVECKLINGSPROFIL</span><h3>${esc(player.full_name||'Spelare')}</h3><p>${player.shirt_number?'#'+player.shirt_number+' · ':''}Senast uppföljd: ${esc(dateText(follow&&follow.created_at))}</p></header><div class="development-workflow-card"><small>MITT UTVECKLINGSMÅL</small><strong>${esc(data.goal&&data.goal.title||'Inget aktivt mål')}</strong></div><div class="development-workflow-card"><small>AKTUELLT FOKUS</small><strong>${esc(data.focus&&data.focus.focus_text||'Inget aktivt fokus')}</strong></div>`;
if(data.proposal)html+=`<div class="development-proposal" data-entity-type="goal_proposal" data-entity-id="${data.proposal.id}"><small>NYTT MÅLFÖRSLAG</small><strong>${esc(data.proposal.proposed_goal_text)}</strong>${data.proposal.coach_comment?`<p>${esc(data.proposal.coach_comment)}</p>`:''}${role==='player'?`<div class="development-actions"><button data-proposal="accepted">GODKÄNN</button><button class="secondary" data-proposal="rejected">BEHÅLL MITT MÅL</button></div>`:''}</div>`;
if(leader(role))html+=`<details class="development-action"><summary>REGISTRERA UPPFÖLJNING</summary><textarea class="development-entry-comment" rows="4" placeholder="Vad pratade ni om?" required></textarea><label><input type="radio" name="developmentVisibility-${player.id}" value="player_visible" checked> Synlig för spelaren</label><label><input type="radio" name="developmentVisibility-${player.id}" value="leaders_only"> Endast ledare</label><button data-save-entry>SPARA UPPFÖLJNING</button><p class="development-form-message"></p></details><details class="development-action"><summary>FÖRESLÅ ÄNDRING AV MÅL</summary><textarea class="development-goal-text" rows="3" placeholder="Föreslaget mål" required></textarea><textarea class="development-goal-comment" rows="2" placeholder="Kommentar till spelaren (valfri)"></textarea><button data-save-proposal>SKICKA FÖRSLAG</button><p class="development-form-message"></p></details>`;
html+='<section class="development-history"><h4>Uppföljningar & anteckningar</h4>'+data.entries.map(e=>`<article class="development-entry" data-entity-type="development_entry" data-entity-id="${e.id}"><div><strong>${e.entry_type==='follow_up'?'Uppföljning':'Anteckning'}</strong>${e.visibility==='leaders_only'?'<span class="leader-only">Endast ledare</span>':''}</div><small>${esc(dateText(e.created_at))}</small><p>${esc(e.comment)}</p></article>`).join('')+'</section></section>';c.innerHTML=html;
c.onclick=async function(ev){const save=ev.target.closest('[data-save-entry]'),proposal=ev.target.closest('[data-save-proposal]'),decision=ev.target.closest('[data-proposal]');try{if(save){const d=save.closest('details'),comment=d.querySelector('.development-entry-comment').value,visibility=d.querySelector('input[type=radio]:checked').value,valid=root.KronangDevelopmentWorkflow.validateDevelopmentEntry(comment,visibility);if(!valid.ok){d.querySelector('.development-form-message').textContent=valid.message;return;}save.disabled=true;const{error}=await root.kronangSupabase.rpc('leader_create_development_entry',{p_player_id:player.id,p_comment:comment,p_visibility:visibility,p_entry_type:'follow_up'});if(error)throw error;await openPlayerDevelopmentWorkflow(opts);root.dispatchEvent(new CustomEvent('kronang:development-updated'));}else if(proposal){const d=proposal.closest('details'),text=d.querySelector('.development-goal-text').value,comment=d.querySelector('.development-goal-comment').value,valid=root.KronangDevelopmentWorkflow.validateGoalProposal(text);if(!valid.ok){d.querySelector('.development-form-message').textContent=valid.message;return;}proposal.disabled=true;const{error}=await root.kronangSupabase.rpc('leader_propose_development_goal',{p_player_id:player.id,p_goal_text:text,p_comment:comment});if(error)throw error;await openPlayerDevelopmentWorkflow(opts);}else if(decision){decision.disabled=true;const{error}=await root.kronangSupabase.rpc('player_respond_goal_proposal',{p_proposal_id:data.proposal.id,p_decision:decision.dataset.proposal});if(error)throw error;await openPlayerDevelopmentWorkflow(opts);if(root.KronangDevelopmentNotifications)root.KronangDevelopmentNotifications.refresh();}}catch(err){console.error('Utvecklingsflöde:',err);const d=ev.target.closest('details');if(d)d.querySelector('.development-form-message').textContent='Det gick inte att spara. Försök igen.';}};
}catch(err){console.error('Kunde inte öppna utvecklingsprofil:',err);c.innerHTML='<p>Utvecklingsprofilen kunde inte hämtas.</p>';}}
async function mountOwnPlayerProfile(){if(!root||!root.kronangSupabase||typeof document==='undefined')return;const page=document.getElementById('developmentPage');if(!page||document.getElementById('ownDevelopmentWorkflow'))return;const{data:s}=await root.kronangSupabase.auth.getSession();if(!s.session)return;const uid=s.session.user.id,{data:profile}=await root.kronangSupabase.from('profiles').select('role').eq('id',uid).maybeSingle();if(!profile||profile.role!=='player')return;const{data:player}=await root.kronangSupabase.from('players').select('id,full_name,shirt_number,profile_id').eq('profile_id',uid).maybeSingle();if(!player)return;const host=document.createElement('section');host.id='ownDevelopmentWorkflow';host.className='card';const grid=page.querySelector('.development-grid');page.insertBefore(host,grid);await openPlayerDevelopmentWorkflow({container:host,role:'player',player});}
const profileApi={buildDevelopmentProfileModel,canRegisterDevelopmentFollowUp,canProposeDevelopmentGoal,canEditOwnDevelopmentGoal,openPlayerDevelopmentWorkflow,mountOwnPlayerProfile};if(typeof module!=='undefined'&&module.exports)module.exports=profileApi;if(root){root.KronangDevelopmentProfile=profileApi;setTimeout(mountOwnPlayerProfile,900);}
})(typeof window!=='undefined'?window:null);
