(function(root){
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
function roleLabel(role){return role==='admin'?'Admin':role==='coach'?'Ledare':'Spelare';}
function timeLabel(value){try{return new Intl.DateTimeFormat('sv-SE',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(value));}catch{return'';}}
async function open(opts){opts=opts||{};let playerId=opts.playerId;if(!playerId&&root.KronangPlayerChatData)playerId=await root.KronangPlayerChatData.ownPlayerId();if(!playerId)return;
 let overlay=document.getElementById('playerChatOverlay');if(overlay)overlay.remove();overlay=el('div','player-chat-overlay');overlay.id='playerChatOverlay';const dialog=el('section','player-chat-dialog');dialog.setAttribute('role','dialog');dialog.setAttribute('aria-modal','true');
 const head=el('header','player-chat-header'),titles=el('div');titles.append(el('strong','',opts.playerName||'Meddelanden'),el('small','','Privat dialog mellan spelaren och ledarstaben'));const close=el('button','player-chat-close','×');close.type='button';close.setAttribute('aria-label','Stäng');head.append(titles,close);
 const list=el('div','player-chat-list');list.setAttribute('aria-live','polite');const form=el('form','player-chat-form'),input=el('textarea','player-chat-input'),send=el('button','player-chat-send','SKICKA'),status=el('p','player-chat-status');input.maxLength=2000;input.rows=2;input.placeholder='Skriv ett meddelande…';send.type='submit';form.append(input,send);dialog.append(head,list,form,status);overlay.append(dialog);document.body.append(overlay);
 const render=async()=>{list.replaceChildren(el('p','player-chat-loading','Hämtar meddelanden…'));try{const rows=await root.KronangPlayerChatData.listMessages(playerId);list.replaceChildren();if(!rows.length)list.append(el('p','player-chat-empty','Inga meddelanden ännu. Skriv gärna först.'));for(const m of rows){const own=(await root.kronangSupabase.auth.getUser()).data.user?.id===m.sender_profile_id;const bubble=el('article','player-chat-bubble '+(own?'is-own':'is-other'));const meta=el('div','player-chat-meta');meta.append(el('strong','',m.sender?.full_name||roleLabel(m.sender?.role)),el('span','',roleLabel(m.sender?.role)+' · '+timeLabel(m.created_at)));bubble.append(meta,el('p','',m.body));list.append(bubble);}list.scrollTop=list.scrollHeight;await root.KronangPlayerChatData.markConversationRead(playerId);root.dispatchEvent(new CustomEvent('kronang:player-chat-read',{detail:{playerId}}));}catch(err){list.replaceChildren(el('p','player-chat-error','Kunde inte hämta meddelanden.'));console.error(err);}};
 close.addEventListener('click',()=>overlay.remove());overlay.addEventListener('click',e=>{if(e.target===overlay)overlay.remove();});
 form.addEventListener('submit',async e=>{e.preventDefault();const draft=input.value;const v=root.KronangPlayerChatData.validateMessage(draft);if(!v.ok){status.textContent=v.error;return;}send.disabled=true;status.textContent='';try{await root.KronangPlayerChatData.sendMessage(playerId,v.body);input.value='';await render();root.dispatchEvent(new CustomEvent('kronang:player-chat-sent',{detail:{playerId}}));}catch(err){input.value=draft;status.textContent='Kunde inte skicka. Ditt meddelande finns kvar.';console.error(err);}finally{send.disabled=false;}});
 await render();input.focus();
}
const api={open,roleLabel,timeLabel};if(typeof module!=='undefined'&&module.exports)module.exports=api;if(root)root.KronangPlayerChat=api;
})(typeof window!=='undefined'?window:null);