const test=require('node:test');const assert=require('node:assert/strict');
const {buildDevelopmentProfileModel,canRegisterDevelopmentFollowUp,canProposeDevelopmentGoal,canEditOwnDevelopmentGoal,goalProposalPlayerPresentation,developmentProfileSectionOrder,activeGoalPresentation}=require('../development-profile.js');
test('leaders get coach actions and player does not',()=>{assert.equal(canRegisterDevelopmentFollowUp('coach'),true);assert.equal(canRegisterDevelopmentFollowUp('admin'),true);assert.equal(canRegisterDevelopmentFollowUp('player'),false);assert.equal(canProposeDevelopmentGoal('coach'),true);});
test('player can edit own goal only',()=>{assert.equal(canEditOwnDevelopmentGoal('player',true),true);assert.equal(canEditOwnDevelopmentGoal('player',false),false);assert.equal(canEditOwnDevelopmentGoal('parent',true),false);});
test('leaders-only entries are excluded from player profile model',()=>{const model=buildDevelopmentProfileModel({role:'player',player:{id:'p1'},entries:[{id:'a',visibility:'player_visible',comment:'Synlig'},{id:'b',visibility:'leaders_only',comment:'Intern'}]});assert.deepEqual(model.entries.map(x=>x.id),['a']);});
test('parent receives no personal development model',()=>{const model=buildDevelopmentProfileModel({role:'parent',player:{id:'p1'},entries:[{id:'a',visibility:'player_visible'}]});assert.equal(model.allowed,false);assert.deepEqual(model.entries,[]);});
test('pending goal proposal is presented as a clear player action',()=>{const view=goalProposalPlayerPresentation('player',{id:'g1',status:'pending',proposed_goal_text:'Bättre första touch'});assert.equal(view.kicker,'NYTT FRÅN DIN LEDARE');assert.equal(view.explainer,'Din ledare föreslår ett nytt utvecklingsmål');assert.equal(view.acceptLabel,'GODKÄNN MÅL');assert.equal(view.changeLabel,'FÖRESLÅ ÄNDRING');assert.equal(view.isActionRequired,true);});
test('pending player action is ordered before current goal and focus',()=>{assert.deepEqual(developmentProfileSectionOrder('player',{status:'pending'}),['proposal','goal','focus']);assert.deepEqual(developmentProfileSectionOrder('player',null),['goal','focus','proposal']);assert.deepEqual(developmentProfileSectionOrder('coach',{status:'pending'}),['goal','focus','proposal']);});
test('active goal is highlighted for the player',()=>{assert.deepEqual(activeGoalPresentation('player',{id:'goal1',status:'active'}),{highlight:true,className:'player-active-goal'});assert.deepEqual(activeGoalPresentation('coach',{id:'goal1',status:'active'}),{highlight:false,className:''});assert.deepEqual(activeGoalPresentation('player',null),{highlight:false,className:''});});
