const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');
test('entrypoints keep chat hidden from parent and pending roles',()=>{const s=fs.readFileSync('player-chat-entrypoints.js','utf8');assert.match(s,/canUseOwnPlayerChat/);assert.match(s,/canUsePlayerChatAsLeader/);});
test('player public profile exposes canonical player id for chat',()=>{const s=fs.readFileSync('player-public-profile-v2.js','utf8');assert.match(s,/select\('id,/);assert.match(s,/dataset\.playerId/);});
test('unread module renders numeric count and hides zero',()=>{const s=fs.readFileSync('player-chat-unread.js','utf8');assert.match(s,/textContent\s*=\s*String\(count\)/);assert.match(s,/count\s*>\s*0/);});
test('player own chat card is removed from Development when messages gets its own nav',()=>{const s=fs.readFileSync('player-chat-entrypoints.js','utf8');assert.match(s,/querySelectorAll\('\[data-player-chat-own\]'\)/);assert.match(s,/\.remove\(\)/);assert.doesNotMatch(s,/Meddelanden från ledarstaben/);});
test('bottom navigation has dedicated messages action outside page navigation',()=>{const html=fs.readFileSync('index.html','utf8');assert.match(html,/class="message-nav-item"[^>]*data-player-chat-nav/);assert.match(html,/data-message-chat-badge/);assert.doesNotMatch(html,/class="nav-item"[^>]*data-player-chat-nav/);});
test('messages action routes player directly and leaders to inbox with shared unread badge',()=>{const s=fs.readFileSync('player-chat-inbox.js','utf8');assert.match(s,/canUseOwnPlayerChat/);assert.match(s,/canUsePlayerChatAsLeader/);assert.match(s,/openMessages/);assert.match(s,/data-message-chat-badge/);assert.match(s,/openInbox/);});

test('messages nav uses the shared navigation icon family',()=>{const html=fs.readFileSync('index.html','utf8'),home=fs.readFileSync('home-player-header.js','utf8'),css=fs.readFileSync('player-chat.css','utf8');assert.match(html,/data-message-nav-icon/);assert.match(home,/message:'<svg/);assert.match(home,/buildNavIcon\('message'\)/);assert.match(css,/stroke-width:1\.8/);assert.match(css,/width:22px;height:22px/);});

test('messages nav label matches other nav typography',()=>{const css=fs.readFileSync('player-chat.css','utf8');assert.match(css,/\.message-nav-item small\{font-size:10px;font-weight:700;letter-spacing:\.15px/);assert.doesNotMatch(css,/\.message-nav-item small\{font-size:8px/);});

test('messages nav appears with resolved bottom nav and unread refresh has no startup delay',()=>{const html=fs.readFileSync('index.html','utf8'),css=fs.readFileSync('player-chat.css','utf8'),inbox=fs.readFileSync('player-chat-inbox.js','utf8');assert.match(html,/data-player-chat-nav aria-label="Öppna meddelanden">/);assert.match(css,/body\[data-access-role="parent"\] \.message-nav-item/);assert.match(css,/body\[data-access-role="pending"\] \.message-nav-item/);assert.doesNotMatch(inbox,/setTimeout\(refresh,1700\)/);assert.match(inbox,/bindNav\(\);refresh\(\);/);});
