const assert = require('assert');
const { normalizePlayer, validatePlayerInput, formatSwedishBirthDate, canManageRoster, formatTeamRoleMarker, buildRosterCardModel } = require('../player-roster.js');
assert.strictEqual(canManageRoster('coach'), true);
assert.strictEqual(canManageRoster('admin'), true);
assert.strictEqual(canManageRoster('player'), false);
assert.strictEqual(canManageRoster('parent'), false);
assert.strictEqual(canManageRoster('pending'), false);
assert.deepStrictEqual(normalizePlayer({id:'1',full_name:' Axel Venhagen ',mobile_phone:' 0727 ',birth_date:'2011-07-15',shirt_number:57,is_active:true,profile_id:null}),{id:'1',name:'Axel Venhagen',mobile:'0727',birthDate:'2011-07-15',shirtNumber:57,position:'',teamRole:'',isActive:true,profileId:null,avatarUrl:'',avatarPath:''});
assert.strictEqual(normalizePlayer({id:'2',full_name:'Bildspelare',avatar_url:'players/2/avatar.jpg',avatar_resolved:'https://signed.example/avatar.jpg'}).avatarUrl,'https://signed.example/avatar.jpg');
assert.strictEqual(normalizePlayer({id:'2',full_name:'Bildspelare',avatar_url:'players/2/avatar.jpg'}).avatarPath,'players/2/avatar.jpg');
assert.strictEqual(validatePlayerInput({name:'   '}).ok, false);
assert.strictEqual(validatePlayerInput({name:'Axel',shirtNumber:''}).ok, true);
assert.strictEqual(validatePlayerInput({name:'Axel',shirtNumber:0}).ok, false);
assert.strictEqual(validatePlayerInput({name:'Axel',shirtNumber:100}).ok, false);
assert.strictEqual(formatSwedishBirthDate('2011-07-15'),'15 juli 2011');
assert.strictEqual(buildRosterCardModel({full_name:'Axel',birth_date:'2011-07-15'},'admin').birthDate,'15 juli 2011');
assert.strictEqual(buildRosterCardModel({full_name:'Axel',birth_date:'2011-07-15'},'coach').birthDate,'2011');
assert.strictEqual(buildRosterCardModel({full_name:'Axel',birth_date:'2011-07-15'},'player').birthDate,'2011');
assert.strictEqual(buildRosterCardModel({full_name:'Axel',birth_date:'2011-07-15'},'parent').birthDate,'2011');
assert.strictEqual(formatTeamRoleMarker('captain'), '(K)');
assert.strictEqual(formatTeamRoleMarker('vice_captain'), '(VK)');
assert.strictEqual(formatTeamRoleMarker(''), '');
console.log('player roster tests passed');
