const assert = require('assert');
const fs = require('fs');
const roster = require('../player-roster.js');
const archive = require('../player-roster-archive.js');
const { buildRosterCardModel, shouldUseCompactLeaderTeamView } = roster;
const { getArchiveActionLabel, PLAYER_ARCHIVE_CONFIRM_TEXT, canArchivePlayer } = archive;

assert.deepStrictEqual(buildRosterCardModel({full_name:'Axel',shirt_number:17,is_active:true,mobile_phone:'0701',birth_date:'2011-07-15'},'admin'),{name:'Axel',number:'#17',mobile:'0701',birthDate:'15 juli 2011',position:'',teamRole:'',actionLabel:'Ta bort från truppen',isActive:true});
assert.deepStrictEqual(buildRosterCardModel({full_name:'Roney',shirt_number:null,is_active:false,mobile_phone:null,birth_date:null},'admin'),{name:'Roney',number:'',mobile:'',birthDate:'',position:'',teamRole:'',actionLabel:'Återaktivera',isActive:false});
assert.equal(getArchiveActionLabel(true),'Ta bort');
assert.equal(getArchiveActionLabel(false),'Återaktivera');
assert.ok(PLAYER_ARCHIVE_CONFIRM_TEXT.includes('SportAdmin påverkas inte'), 'archive confirmation must explicitly say SportAdmin is unaffected');
assert.ok(PLAYER_ARCHIVE_CONFIRM_TEXT.includes('historik sparas'), 'archive confirmation must explain that player history is preserved');
assert.equal(canArchivePlayer('admin',true),true,'active admin may archive a player');
assert.equal(canArchivePlayer('coach',true),false,'coach must never archive a player');
assert.equal(canArchivePlayer('player',true),false,'player must never archive a player');
assert.equal(canArchivePlayer('parent',true),false,'parent must never archive a player');
assert.equal(canArchivePlayer('admin',false),false,'inactive admin must never archive a player');

assert.equal(shouldUseCompactLeaderTeamView('admin'), true, 'admin should get compact leader team view');
assert.equal(shouldUseCompactLeaderTeamView('coach'), true, 'coach should get compact leader team view');
assert.equal(shouldUseCompactLeaderTeamView('player'), false, 'player should keep normal team view');
assert.equal(shouldUseCompactLeaderTeamView('parent'), false, 'parent should keep normal team view');

const js = fs.readFileSync('player-roster.js', 'utf8');
const archiveJs = fs.readFileSync('player-roster-archive.js', 'utf8');
const css = fs.readFileSync('player-roster.css', 'utf8');
const index = fs.readFileSync('index.html', 'utf8');
const archiveMigrationPath='supabase/migrations/202609090004_admin_only_player_archive.sql';
assert.ok(fs.existsSync(archiveMigrationPath),'admin-only player archive migration must exist');
const archiveMigration=fs.readFileSync(archiveMigrationPath,'utf8');
assert.ok(js.includes("classList.toggle('leader-team-view'") || js.includes('classList.toggle("leader-team-view"'), 'leader/admin role should explicitly activate the compact team class');
assert.ok(archiveJs.includes('Borttagna/arkiverade spelare'), 'inactive roster section should be labelled as archived players');
assert.ok(archiveJs.includes('player-public-profile-archive'), 'archive action should be rendered inside the opened player profile');
assert.ok(archiveJs.includes("closest('[data-roster-active]')"), 'archive UX should identify clicks from the active roster list');
assert.ok(archiveJs.includes("button.style.display='none'"), 'active roster list should hide the old remove button');
assert.ok(archiveJs.includes("rpc('admin_archive_player'"), 'profile archive action must use the admin-only server RPC');
assert.ok(!archiveJs.includes("from('players').update({is_active:false"), 'browser must not archive players through direct table update');
assert.ok(archiveJs.includes("button.textContent=getArchiveActionLabel(true)"), 'opened player profile remove button should use the short Ta bort label');
assert.ok(archiveJs.includes("profile.querySelector('.player-public-profile-role')"), 'remove button should look for the captain/vice-captain badge');
assert.ok(archiveJs.includes('roleBadge.after(button)'), 'remove button should be placed immediately below the captain/vice-captain badge');
assert.ok(archiveJs.includes('window.confirm('), 'removing an active player should require confirmation');
assert.ok(archiveJs.includes('Spelaren tas bara bort från appen'), 'confirmation should explain local-only removal');
assert.ok(/admin_archive_player/i.test(archiveMigration),'migration must define an admin-only archive RPC');
assert.ok(/old\.is_active\s*=\s*true[\s\S]*new\.is_active\s*=\s*false/i.test(archiveMigration),'migration must guard active-to-inactive player transitions');
assert.ok(/current_profile_role\(\)[\s\S]*admin/i.test(archiveMigration),'database archive guard must require admin role');
assert.ok(css.includes('#teamPage.leader-team-view.active'), 'compact layout should be tied to the explicit leader-team-view class');
assert.ok(!css.includes('#teamPage:has(#playerRosterSection).active'), 'compact layout must not depend on :has() for layout activation');
assert.ok(css.includes('grid-template-columns:repeat(2,minmax(0,1fr))'), 'leader tools should render two by two on mobile');
assert.ok(css.includes('align-items:start'), 'paired mobile admin cards must keep independent heights instead of stretching to the tallest editor');
assert.ok(/player-roster-avatar\{width:48px;height:48px/.test(css), 'roster list thumbnail should keep its compact 48px size');
assert.ok(/player-roster-card-actions button\{min-height:30px/.test(css), 'roster edit buttons should be compact on mobile');
assert.ok(css.includes('.player-roster-avatar:not(:has(img))::after'), 'missing roster images should have a visible placeholder label');
assert.ok(css.includes('content:"BILD\\A KOMMER"'), 'missing roster images should say BILD KOMMER');
assert.ok(css.includes('#teamPostComposer:has(#teamPostForm:not([hidden]))>#openTeamPostComposer{display:none}'), 'open post button must disappear while the editor is open');
assert.ok(css.includes('#teamPage.leader-team-view.active>#teamFocusManager:has(#teamFocusForm:not([hidden])){grid-column:1/-1;min-height:0}'), 'open focus editor should use the full mobile width without stretching its neighbour');
assert.ok(css.includes('#teamFocusManager:has(#teamFocusForm:not([hidden]))>#openTeamFocusManager{display:none}'), 'focus opener must disappear while focus editor is open');
assert.ok(css.includes('#teamPage.leader-team-view.active>#teamChallengeManager:has(#teamChallengeForm:not([hidden])){grid-column:1/-1;min-height:0}'), 'open challenge editor should use the full mobile width without stretching its neighbour');
assert.ok(css.includes('#teamChallengeManager:has(#teamChallengeForm:not([hidden]))>#openTeamChallengeManager{display:none}'), 'challenge opener must disappear while challenge editor is open');
assert.ok(index.includes('player-roster.css?v=8'), 'roster css cache version must be current');
assert.ok(index.includes('player-roster.js?v=11'), 'roster js cache version must be current after fetch-before-close editor fix');
assert.ok(index.includes('player-roster-archive.js?v=4'), 'player profile archive UX cache version must be current');
console.log('player roster ui tests passed');
