const fs=require('fs');
function read(path){return fs.readFileSync(path,'utf8');}
const migration=read('supabase/migrations/202609081500_sportadmin_roster_sync.sql');
const autoMigration=read('supabase/migrations/202609090001_auto_import_sportadmin_players.sql');
const fn=read('supabase/functions/sportadmin-roster-sync/index.ts');
const ui=read('sportadmin-sync-admin.js');
const adminCenter=read('admin-center.js');
const schedule=read('.github/workflows/sportadmin-roster-daily.yml');
if(!/sportadmin_player_candidates/i.test(migration)) throw new Error('candidate table missing');
if(!/status[^\n]*(pending|approved|dismissed)/i.test(migration)) throw new Error('candidate statuses missing');
if(!/acknowledge_sportadmin_player_candidate/i.test(autoMigration)) throw new Error('SportAdmin acknowledgement RPC missing');
if(!/reviewed_at is null/i.test(autoMigration)) throw new Error('unseen SportAdmin import query missing');
if(!/schedule:/i.test(schedule)||!/cron:/i.test(schedule)) throw new Error('daily schedule missing');
if(!/sportadmin-roster-sync/i.test(schedule)) throw new Error('scheduled sync target missing');
if(!/260563/.test(fn)) throw new Error('P2011 SportAdmin roster source missing');
if(!/224799/.test(fn)) throw new Error('P2009-2010 SportAdmin roster source missing');
if(!/SOURCES/.test(fn)||!/sportadmin_junior/.test(fn)) throw new Error('combined junior roster source missing');
if(!/userRow/i.test(fn)||!/Spelare/i.test(fn)) throw new Error('SportAdmin roster row parser missing');
if(!/players/i.test(fn)||!/full_name/i.test(fn)) throw new Error('existing player comparison missing');
if(/birth|birthday|phone|email|guardian|parent/i.test(fn)) throw new Error('SportAdmin sync must not import personal details beyond name');
if(!/from\('players'\)\.insert/.test(fn)||!/status:'approved'/.test(fn)) throw new Error('new SportAdmin players must be added automatically');
if(!/SPORTADMIN/i.test(ui)||!/MARKERA SOM SEDD/i.test(ui)) throw new Error('admin SportAdmin notification UI missing');
if(/GODKÄNN|AVVISA/.test(ui)) throw new Error('SportAdmin imports must not require manual approval');
if(!/sportadmin-roster-sync/.test(adminCenter)) throw new Error('Admincenter manual sync action missing');
if(/data-sportadmin-sync/.test(ui)) throw new Error('legacy SportAdmin UI must not expose a second manual sync action');
if(!/triggeredBy/.test(fn)||!/scheduled/.test(fn)||!/admin/.test(fn)) throw new Error('sync trigger classification missing');
if(!/sportadmin_sync_runs/.test(fn)) throw new Error('sync history recording missing');
if(!/started_at/.test(fn)||!/finished_at/.test(fn)) throw new Error('sync run timestamps missing');
if(!/status:\s*['"]success['"]/.test(fn)||!/status:\s*['"]failure['"]/.test(fn)) throw new Error('success/failure sync run recording missing');
if(!/found/.test(fn)||!/imported/.test(fn)||!/error_message/.test(fn)) throw new Error('sync run result metadata missing');
console.log('sportadmin roster sync contract ok');
