const fs=require('fs');
const player=fs.readFileSync('player-public-profile-v2.js','utf8');
const staff=fs.readFileSync('team-staff.js','utf8');
if(!/player-public-profile-avatar-wrap/.test(player)) throw new Error('Player profile needs avatar wrapper for shirt badge');
if(!/player-public-profile-number-v2/.test(player)||!/position:absolute/.test(player)) throw new Error('Player number must overlay avatar');
if(!/text-transform:uppercase/.test(player)) throw new Error('Player position must be uppercase');
if(!/font-weight:(?:700|800|900)/.test(player)) throw new Error('Player signature must be bold');
if(!/team-staff-profile-signature/.test(staff)) throw new Error('Staff profile needs matching signature styling');
if(!/team-staff-profile-about/.test(staff)) throw new Error('Staff profile needs matching about card');
if(!/text-transform:uppercase/.test(staff)) throw new Error('Staff role must be uppercase');
console.log('unified team profile layout ok');
