const test=require('node:test');const assert=require('node:assert/strict');const create=require('../push-subscriptions.js').create;
function phone(overrides={}){let sub=null,stored={};const calls=[];const root={isSecureContext:true,PushManager:function(){},Notification:{permission:'default',requestPermission(){calls.push('permission');this.permission='granted';return Promise.resolve('granted');}},navigator:{userAgent:'iPhone',standalone:true,serviceWorker:{async register(){return reg;},async getRegistration(){return reg;},ready:null},async clearAppBadge(){calls.push('clear');}},matchMedia:()=>({matches:false}),localStorage:{getItem:k=>stored[k]||null,setItem:(k,v)=>stored[k]=v,removeItem:k=>delete stored[k]},atob:s=>Buffer.from(s,'base64').toString('binary'),kronangSupabase:{auth:{async getUser(){return {data:{user:{id:root.owner||'one'}}};}},async rpc(name,args){calls.push(name);if(root.fail&&name==='register_push_subscription')return {error:new Error('network')};return {data:name==='register_push_subscription'?'sub-id':{}};}}};
const reg={pushManager:{async getSubscription(){return sub;},async subscribe(){calls.push('subscribe');sub={endpoint:'https://web.push.apple.com/test',toJSON:()=>({endpoint:sub.endpoint,keys:{p256dh:'key',auth:'auth'}}),async unsubscribe(){calls.push('unsubscribe');sub=null;return true;}};return sub;}}};root.navigator.serviceWorker.ready=Promise.resolve(reg);Object.assign(root,overrides);return {root,calls,reg,getSub:()=>sub};}
test('iPhone browser tab explains home-screen installation',()=>{const f=phone();f.root.navigator.standalone=false;const s=create(f.root).support();assert.equal(s.supported,false);assert.match(s.reason,/hemskärmen/);});
test('permission is requested synchronously on activation click',async()=>{const f=phone(),api=create(f.root);api.configure({ownerId:'one',publicKey:'A'.repeat(87)});const promise=api.activate();assert.equal(f.calls[0],'permission');await promise;assert.ok(f.getSub());});
test('denied permission supplies phone settings recovery',async()=>{const f=phone();f.root.Notification.permission='denied';const api=create(f.root);api.configure({ownerId:'one',publicKey:'A'.repeat(87)});await assert.rejects(api.activate(),/inställningar/i);});
test('failed registration does not leave a successful local subscription',async()=>{const f=phone(),api=create(f.root);api.configure({ownerId:'one',publicKey:'A'.repeat(87)});f.root.fail=true;await assert.rejects(api.activate());assert.equal(f.getSub(),null);f.root.fail=false;await api.activate();assert.ok(f.getSub());});
test('account switch unsubscribes old phone, never registers new user automatically',async()=>{const f=phone(),api=create(f.root);api.configure({ownerId:'one',publicKey:'A'.repeat(87)});await api.activate();const n=f.calls.filter(x=>x==='register_push_subscription').length;await api.reconcile('two');assert.equal(f.getSub(),null);assert.equal(f.calls.filter(x=>x==='register_push_subscription').length,n);});
test('disabling one device leaves another device subscribed',async()=>{const a=phone(),b=phone(),aa=create(a.root),bb=create(b.root);for(const api of [aa,bb]){api.configure({ownerId:'one',publicKey:'A'.repeat(87)});await api.activate();}await aa.disable();assert.equal(a.getSub(),null);assert.ok(b.getSub());assert.ok(a.calls.includes('disable_push_subscription'));});
test('logout cleanup works with service worker support but no PushManager',async()=>{const f=phone();f.root.navigator.serviceWorker={register:async()=>({}),ready:Promise.resolve({}),getRegistration:async()=>({})};await create(f.root).detachBeforeLogout();});
test('logout without subscription does not require successful worker registration',async()=>{const f=phone();f.root.navigator.serviceWorker={register:async()=>{throw new Error('offline');},getRegistration:async()=>null};await create(f.root).detachBeforeLogout();});
